apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java
  namespace: development
  labels:
    app: hello-world-java
    tier: backend
spec:
  selector:
    matchLabels:
      app: hello-world-java
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-java
    spec:
      automountServiceAccountToken: false
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
          sizeLimit: 100Mi
      securityContext:
        runAsUser: 1199
        runAsGroup: 1199
      containers:
      - name: hello-world-java
        image: ${AWS_ECR}:${BUILD_ID}
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
        volumeMounts:
        - mountPath: /tmp
          name: tmp
          subPath: tmp
        securityContext:
          runAsUser: 1199
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        imagePullPolicy: Always
        resources:
          limits:
            memory: 700Mi
            cpu: 500m
          requests:
            memory: 512Mi
            cpu: 250m
