apiVersion: v1
kind: Service
metadata:
  name: hello-world-java
  namespace: development
  labels:
    app: hello-world-java
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-java
  type: LoadBalancer
